name: Deploy React (Self Hosted)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # 3️⃣ Install Dependencies
      - name: Install Dependencies
        run: |
          rm -rf node_modules
          npm install

      # 4️⃣ Build React App
      - name: Build React App
        run: |
          npm run build

      # 5️⃣ Deploy to server folder
      - name: Deploy Build
        run: |
          sudo rm -rf /home/ec2-user/frontend
          sudo mkdir -p /home/ec2-user/frontend

          # If using Vite → dist
          if [ -d dist ]; then
            sudo cp -r dist/* /home/ec2-user/frontend
          fi

          # If using CRA → build
          if [ -d build ]; then
            sudo cp -r build/* /home/ec2-user/frontend
          fi

      # 6️⃣ Restart Nginx
      - name: Restart Nginx
        run: sudo systemctl restart nginx
